### ISSUE TITLE
Crash on New Game select

### ISSUE THREAD

**Issue by alexeagleson** [tylervipond/apprentice#52]
I'm getting an occasional crash when selecting the "New Game" option.  Seems to happen about 25% of the time, had never seen this happen previously.

I'm on the `things-light-on-fire` branch

Error is:

`thread 'main' panicked at 'UniformSampler::sample_single: low >= high', C:\Users\Alex\.cargo\registry\src\github.com-1ecc6299db9ec823\rand-0.7.3\src\distributions\uniform.rs:468:1`

Somehow connected to this maybe?

https://docs.rs/rand/0.5.0/rand/distributions/uniform/trait.UniformSampler.html

**Comment by tylervipond** [comment]
yeah, I believe this happens because on line 165 of `level_builders::build` we get random between 2 and `rects.len()` which is populated on 164, the length of which is determined on line 38 with `rng.range(2, rects.len() as i32)` which means that line 165 can be `rng.range(2, 2);` which would throw. I think I just left some code in after the refactor. I believe that lines 34 - 44 are unnecessary.
